[package]
name = "nest"
version = "0.1.0"
authors = ["Michael Williams <michael.williams@enspiral.com>"]
edition = "2018"

[dependencies]
atomicwrites = "0.2"
common_macros = "0.1"
serde_json = "1.0"
